### ISSUE TITLE
Specific package is not exploding

### ISSUE THREAD

**Issue by yvesgoeleven** [FubuMvcArchive/ripple#168]
Looks like the following package is not exploding through a ripple restore

http://www.nuget.org/packages/Elastacloud.AzureManagement.Fluent/

Ripple simply says, downloading.. exploding.. and doesn't give an exception and nothing else in the logs. But the content is not extracted from the package

There must be something wrong with the package I guess because it only happens on this specific one... (Yet it works fine when installed trough nuget.exe)

**Comment by jeremydmiller** [comment]
Did Nuget find the same version of the package that ripple did?

I don't have any ideas yet.

**Comment by yvesgoeleven** [comment]
Yes, it did find the same version

**Comment by jmarnold** [comment]
I think it's an issue of us using an older version of NuGet.Core. We're using the same "GetFiles" method to do the explosion. Looking at that package, I exploded it manually with 7zip. The dll in there shows up as lib%5CElastacloud.AzureManagement.Fluent.dll in the root instead of in the lib folder.

I'm going to try upgrading us to see if their latest can handle the encoding issues there. Otherwise, we might ask the authors to change their encoding in their nuspec file?

**Comment by jmarnold** [comment]
Looking further, their nuspec doesn't even specify the file. Can we issue a PR to them maybe? It'll be easier to fix it on their end.
