### ISSUE TITLE
Kill the local commands

### ISSUE THREAD

**Issue by jmarnold** [FubuMvcArchive/ripple#177]

**Comment by SimonCropp** [comment]
What does this actually mean?

**Comment by SimonCropp** [comment]
it would seem this issue conflicts with #176

**Comment by jeremydmiller** [comment]
The existing local command doesn't really work anymore after the huge ripple2 effort, and honestly, I'd like to see that mess of over complicated code smell go away.

What Josh & I have talked about is rewriting it from scratch such that ripple local generates the nukpg files locally for the upstream project and explodes that nukpg file right into the downstream project so that we're using almost exactly the same mechanics that we do with restore's, install's, and update's.  I think that ends up with us having much, much less code than what we started with.

**Comment by jmarnold** [comment]
We've talked about doing it in a two phase approach where we kill off the
existing commands and rewrite them later
