### ISSUE TITLE
no `ripple.dependencies.config` files results in `<Nugets>` node being removed 

### ISSUE THREAD

**Issue by SimonCropp** [FubuMvcArchive/ripple#189]
So if there is no `ripple.dependencies.config` in the directory structure then this line 

https://github.com/DarthFubuMVC/ripple/blob/master/src/ripple/Model/ISolutionFiles.cs#L113

reverts the solution load back to classic. which results in the `<Nugets>` node being removed from the `ripple.config`.

Since `ripple.dependencies.config` files are optional ripple should not assume classic if it doesnt find any.

**Comment by jmarnold** [comment]
By "optional", you mean it's optional during init, right? Ripple will
create the file for a project if it doesn't exist. Though, I suppose we
could make that smarter.

**Comment by SimonCropp** [comment]
well my experience was i was setting it up manually. i wanted to test if my dependencies in ripple.config were correct so i did a restore to see if they all came down. but instead of pulling down nugets it deleted my dependencies from ripple.config

**Comment by jmarnold** [comment]
Ah, gotcha. I just kicked off the 3.0 branch on my machine to address the
whole NuGet vs. ripple style organization. I'm strategizing the
ISolutionLoader interface and thinking we do:
1. NugetSolutionLoader (matches when packages.config files are found and no
   ripple.dependencies.config are found)
2. XmlSolutionLoader (matches when any ripple.dependencies.config files are
   found and the ripple.config contains xml)
3. SolutionLoader (matches when any ripple.dependencies.config files are
   found and uses the object block notation)

This additional condition of there not being any ripple.dependencies.config
files for #1 is only because some of the FubuMVC bottles end up packaging
up a packages.config file if you're not careful. The deep search sees the
packages.config file and hilarity ensues.

How does that sound?

**Comment by jmarnold** [comment]
Got it in 3.0.
