### ISSUE TITLE
nuget.xsd namespace is required for ripplized nuspecs

### ISSUE THREAD

**Issue by KevM** [FubuMvcArchive/ripple#6]
If you do not have your nuget specification XML namespaced `ripple restore` currently throws a NullReferenceException

Current nuspec XML required 

``` xml
<?xml version="1.0"?>
<package xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <metadata xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
   <!-- ...-->
 </metadata>
</package>
```

Why is this namespacing in effect? The current nuget spec command does not include the nuget xml namespaces when generating a blank nuspec.

**Comment by jeremydmiller** [comment]
Ripple reads the Xml spec to "know" how to find assemblies and other files and 
move them around.  When I coded that up, the nuspec's I working off of had the 
xsd namespace, so you had to use the namespace to read the Xml file.  If there's 
a way to make it more resilient in the internals, go for it.

It's not a by design limitation at all.
 Jeremy D. Miller
The Shade Tree Developer
jeremydmiller@yahoo.com

---

From: Kevin Miller 
reply@reply.github.com

To: Jeremy D. Miller jeremydmiller@yahoo.com
Sent: Thu, March 8, 2012 11:05:40 AM
Subject: [ripple] nuget.xsd namespace is required for ripplized nuspecs (#6)

If you do not have your nuget specification XML namespaced `ripple restore` 
currently throws a NullReferenceException

Current nuspec XML required 

``` xml
<?xml version="1.0"?>


   <!-- ...-->
</metadata>
</package>
```

Why is this namespacing in effect? The current nuget spec command does not 
include the nuget xml namespaces when generating a blank nuspec.

---

Reply to this email directly or view it on GitHub:
https://github.com/DarthFubuMVC/ripple/issues/6

**Comment by jmarnold** [comment]
I'm calling this one. We can make a new command to generate a nuspec template with the namespacing just to make everything flow if people really want it.
