### ISSUE TITLE
Automated tests for publishing

### ISSUE THREAD

**Issue by Scooletz** [FubuMvcArchive/ripple#77]
Are PublishCommand & LocalNugetCommand unused? I can find no tests. The solution Specifications seems to be unused as well. What's their status?

**Comment by jmarnold** [comment]
I haven't found a great way to ht hose with automated tests just yet. We
use the local-nuget command in the Fubu build server for every build and
its working fine.

I took the publish command for a spin earlier this week to manually test
and it worked. I think the automated test coverage for the publish would
definitely be good to have since its only donee manually by us right now.

**Comment by jmarnold** [comment]
The specifications are used for local ripple ands (local and flo)

**Comment by Scooletz** [comment]
But how add a specification? I find no parameter on LocalNugetCommand to pass it. Note: I'm using Ripple with no Fubu, just as a better NuGet client.

**Comment by jmarnold** [comment]
Your ripple.config has a "NugetSpecFolder" property that defaults to packaging/nuget. Running the local-nuget command will apply to all of the specifications in that directory. Here's an example of how I use it in CI:

ripple local-nuget --version 1.0.1.244 --destination artifacts

Where "1.0.1.244" would be a variable from teamcity.

**Comment by Scooletz** [comment]
Thx for the answer. Now it's clear!
